var hierarchy =
[
    [ "_PAGE", "struct___p_a_g_e.html", null ],
    [ "_win_st", "struct__win__st.html", null ],
    [ "AComponent", "class_a_component.html", [
      [ "AnimationComponent", "class_animation_component.html", null ],
      [ "GameComponent", "class_game_component.html", null ],
      [ "HighScoreComponent", "class_high_score_component.html", null ],
      [ "UIComponent", "class_u_i_component.html", [
        [ "DualTextComponent", "class_dual_text_component.html", null ]
      ] ]
    ] ],
    [ "ActionComponent< linkedElemType, action1Type, action2Type >", "class_action_component.html", null ],
    [ "alias", "structalias.html", null ],
    [ "arcade::Arcade", "classarcade_1_1_arcade.html", null ],
    [ "ArcadeMenu", "class_arcade_menu.html", null ],
    [ "Astar", "class_astar.html", null ],
    [ "entry", "structentry.html", null ],
    [ "fieldnode", "structfieldnode.html", null ],
    [ "formnode", "structformnode.html", null ],
    [ "arcade::GetMap", "structarcade_1_1_get_map.html", null ],
    [ "HashData", "struct_hash_data.html", null ],
    [ "IChrono", "class_i_chrono.html", [
      [ "Chrono< T, U >", "class_chrono.html", null ]
    ] ],
    [ "IGame", "class_i_game.html", [
      [ "AGame", "class_a_game.html", [
        [ "PacmanGame", "class_pacman_game.html", null ],
        [ "Snake", "class_snake.html", null ]
      ] ]
    ] ],
    [ "IGraph", "class_i_graph.html", [
      [ "NCursesGraph", "class_n_curses_graph.html", null ],
      [ "OpenGlGraph", "class_open_gl_graph.html", null ],
      [ "SDLGraph", "class_s_d_l_graph.html", null ]
    ] ],
    [ "invalid_argument", null, [
      [ "arcade::InvalidFileFormatException", "classarcade_1_1_invalid_file_format_exception.html", null ]
    ] ],
    [ "LoadHighScore", "class_load_high_score.html", null ],
    [ "ncr::Menu", "classncr_1_1_menu.html", null ],
    [ "MEVENT", "struct_m_e_v_e_n_t.html", null ],
    [ "name_table_entry", "structname__table__entry.html", null ],
    [ "NCurses", "class_n_curses.html", null ],
    [ "PacmanCharacter", "class_pacman_character.html", [
      [ "Ghost", "class_ghost.html", null ],
      [ "Pacman", "class_pacman.html", null ]
    ] ],
    [ "panel", "structpanel.html", null ],
    [ "panelhook", "structpanelhook.html", null ],
    [ "_win_st::pdat", "struct__win__st_1_1pdat.html", null ],
    [ "arcade::Position", "structarcade_1_1_position.html", null ],
    [ "runtime_error", null, [
      [ "arcade::IncompleteLibraryException", "classarcade_1_1_incomplete_library_exception.html", null ],
      [ "arcade::InitRenderException", "classarcade_1_1_init_render_exception.html", null ],
      [ "arcade::LoadLibraryException", "classarcade_1_1_load_library_exception.html", null ],
      [ "graph::GraphException", "classgraph_1_1_graph_exception.html", [
        [ "NCursesSystemFailed", "class_n_curses_system_failed.html", null ],
        [ "ResizeFailed", "class_resize_failed.html", null ]
      ] ]
    ] ],
    [ "s_cache", "structs__cache.html", null ],
    [ "s_header", "structs__header.html", null ],
    [ "s_highScore", "structs__high_score.html", null ],
    [ "SDL_AssertData", "struct_s_d_l___assert_data.html", null ],
    [ "SDL_atomic_t", "struct_s_d_l__atomic__t.html", null ],
    [ "SDL_AudioCVT", "struct_s_d_l___audio_c_v_t.html", null ],
    [ "SDL_AudioDeviceEvent", "struct_s_d_l___audio_device_event.html", null ],
    [ "SDL_AudioSpec", "struct_s_d_l___audio_spec.html", null ],
    [ "SDL_Color", "struct_s_d_l___color.html", null ],
    [ "SDL_CommonEvent", "struct_s_d_l___common_event.html", null ],
    [ "SDL_ControllerAxisEvent", "struct_s_d_l___controller_axis_event.html", null ],
    [ "SDL_ControllerButtonEvent", "struct_s_d_l___controller_button_event.html", null ],
    [ "SDL_ControllerDeviceEvent", "struct_s_d_l___controller_device_event.html", null ],
    [ "SDL_DisplayMode", "struct_s_d_l___display_mode.html", null ],
    [ "SDL_DollarGestureEvent", "struct_s_d_l___dollar_gesture_event.html", null ],
    [ "SDL_DropEvent", "struct_s_d_l___drop_event.html", null ],
    [ "SDL_Event", "union_s_d_l___event.html", null ],
    [ "SDL_Finger", "struct_s_d_l___finger.html", null ],
    [ "SDL_GameControllerButtonBind", "struct_s_d_l___game_controller_button_bind.html", null ],
    [ "SDL_HapticCondition", "struct_s_d_l___haptic_condition.html", null ],
    [ "SDL_HapticConstant", "struct_s_d_l___haptic_constant.html", null ],
    [ "SDL_HapticCustom", "struct_s_d_l___haptic_custom.html", null ],
    [ "SDL_HapticDirection", "struct_s_d_l___haptic_direction.html", null ],
    [ "SDL_HapticEffect", "union_s_d_l___haptic_effect.html", null ],
    [ "SDL_HapticLeftRight", "struct_s_d_l___haptic_left_right.html", null ],
    [ "SDL_HapticPeriodic", "struct_s_d_l___haptic_periodic.html", null ],
    [ "SDL_HapticRamp", "struct_s_d_l___haptic_ramp.html", null ],
    [ "SDL_JoyAxisEvent", "struct_s_d_l___joy_axis_event.html", null ],
    [ "SDL_JoyBallEvent", "struct_s_d_l___joy_ball_event.html", null ],
    [ "SDL_JoyButtonEvent", "struct_s_d_l___joy_button_event.html", null ],
    [ "SDL_JoyDeviceEvent", "struct_s_d_l___joy_device_event.html", null ],
    [ "SDL_JoyHatEvent", "struct_s_d_l___joy_hat_event.html", null ],
    [ "SDL_JoystickGUID", "struct_s_d_l___joystick_g_u_i_d.html", null ],
    [ "SDL_KeyboardEvent", "struct_s_d_l___keyboard_event.html", null ],
    [ "SDL_Keysym", "struct_s_d_l___keysym.html", null ],
    [ "SDL_MessageBoxButtonData", "struct_s_d_l___message_box_button_data.html", null ],
    [ "SDL_MessageBoxColor", "struct_s_d_l___message_box_color.html", null ],
    [ "SDL_MessageBoxColorScheme", "struct_s_d_l___message_box_color_scheme.html", null ],
    [ "SDL_MessageBoxData", "struct_s_d_l___message_box_data.html", null ],
    [ "SDL_MouseButtonEvent", "struct_s_d_l___mouse_button_event.html", null ],
    [ "SDL_MouseMotionEvent", "struct_s_d_l___mouse_motion_event.html", null ],
    [ "SDL_MouseWheelEvent", "struct_s_d_l___mouse_wheel_event.html", null ],
    [ "SDL_MultiGestureEvent", "struct_s_d_l___multi_gesture_event.html", null ],
    [ "SDL_OSEvent", "struct_s_d_l___o_s_event.html", null ],
    [ "SDL_Palette", "struct_s_d_l___palette.html", null ],
    [ "SDL_PixelFormat", "struct_s_d_l___pixel_format.html", null ],
    [ "SDL_Point", "struct_s_d_l___point.html", null ],
    [ "SDL_QuitEvent", "struct_s_d_l___quit_event.html", null ],
    [ "SDL_Rect", "struct_s_d_l___rect.html", null ],
    [ "SDL_RendererInfo", "struct_s_d_l___renderer_info.html", null ],
    [ "SDL_RWops", "struct_s_d_l___r_wops.html", null ],
    [ "SDL_Surface", "struct_s_d_l___surface.html", null ],
    [ "SDL_SysWMEvent", "struct_s_d_l___sys_w_m_event.html", null ],
    [ "SDL_SysWMinfo", "struct_s_d_l___sys_w_minfo.html", null ],
    [ "SDL_SysWMmsg", "struct_s_d_l___sys_w_mmsg.html", null ],
    [ "SDL_TextEditingEvent", "struct_s_d_l___text_editing_event.html", null ],
    [ "SDL_TextInputEvent", "struct_s_d_l___text_input_event.html", null ],
    [ "SDL_TouchFingerEvent", "struct_s_d_l___touch_finger_event.html", null ],
    [ "SDL_UserEvent", "struct_s_d_l___user_event.html", null ],
    [ "SDL_version", "struct_s_d_l__version.html", null ],
    [ "SDL_WindowEvent", "struct_s_d_l___window_event.html", null ],
    [ "SDL_WindowShapeMode", "struct_s_d_l___window_shape_mode.html", null ],
    [ "SDL_WindowShapeParams", "union_s_d_l___window_shape_params.html", null ],
    [ "SDLTest_CommonState", "struct_s_d_l_test___common_state.html", null ],
    [ "SDLTest_Crc32Context", "struct_s_d_l_test___crc32_context.html", null ],
    [ "SDLTest_Md5Context", "struct_s_d_l_test___md5_context.html", null ],
    [ "SDLTest_RandomContext", "struct_s_d_l_test___random_context.html", null ],
    [ "SDLTest_SurfaceImage_s", "struct_s_d_l_test___surface_image__s.html", null ],
    [ "SDLTest_TestCaseReference", "struct_s_d_l_test___test_case_reference.html", null ],
    [ "SDLTest_TestSuiteReference", "struct_s_d_l_test___test_suite_reference.html", null ],
    [ "tagITEM", "structtag_i_t_e_m.html", null ],
    [ "tagMENU", "structtag_m_e_n_u.html", null ],
    [ "term", "structterm.html", null ],
    [ "termtype", "structtermtype.html", null ],
    [ "TEXT", "struct_t_e_x_t.html", null ],
    [ "tinfo_fkeys", "structtinfo__fkeys.html", null ],
    [ "token", "structtoken.html", null ],
    [ "typenode", "structtypenode.html", null ],
    [ "Vector2< T >", "class_vector2.html", null ],
    [ "Vector2< double >", "class_vector2.html", null ],
    [ "Vector2< int >", "class_vector2.html", null ],
    [ "arcade::WhereAmI", "structarcade_1_1_where_am_i.html", null ],
    [ "ncr::Window", "classncr_1_1_window.html", null ]
];